version: '3'

services:
  flask-app:
    image: notes-app-flask
    container_name: notes-app-flask-container
    build: .
    ports:
      - "6000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python main.py
